[package]
name = "lunacam"
version = "0.1.0"
authors = ["Bobby Reynolds <bobby@reynoldsbd.net>"]
edition = "2018"

[dependencies]
actix = "0.7"
actix-web = "0.7"
base64 = "0.10"
base64-serde = "0.3"
ctrlc = "3.1"
derive_more = "0.14"
env_logger = "0.6"
futures = "0.1.25"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tera = "0.11"
