# Builds a specified variant of the LunaCam SD card image

parameters:
  variant: ''

steps:
- task: NodeTool@0
  displayName: Use Node.js 10.x
  inputs:
    versionSpec: '10.x'
- task: YarnInstaller@3
  displayName: Use Yarn 1.19.0
  inputs:
    versionSpec: '1.19.0'
- task: ShellScript@2
  displayName: Use Sass 1.23.0
  inputs:
    scriptPath: tools/devops/install-sass.sh
    arguments: '"1.23.0" "$(Agent.ToolsDirectory)/Sass/1.23.0/x64"'
    pwsh: true
- script: make ${{ parameters.variant }}-image
  displayName: Build LunaCam Image
