# Builds a specified variant of the LunaCam SD card image

parameters:
  variant: ''

steps:
- task: geeklearningio.gl-vsts-tasks-yarn-dev.yarn-installer-task.YarnInstaller@3
  displayName: Use Yarn 1.19.0
  inputs:
    versionSpec: '1.19.0'
- task: PowerShell@2
  displayName: Use Sass 1.23.0
  inputs:
    filePath: tools/devops/Install-Sass.ps1
    arguments: -Version 1.23.0 -Destination $(Agent.ToolsDirectory)/Sass/1.23.0/x64
    pwsh: true
- script: make ${{ parameters.variant }}-image
  displayName: Build LunaCam Image
