[package]
name = "lunacam-daemon"
version = "0.1.0"
authors = ["Bobby Reynolds <bobby@reynoldsbd.net>"]
edition = "2018"

[dependencies]
actix-web = "1.0"
env_logger = "0.6"
lazy_static = "1.3"
lunacam = { path = ".." }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
tokio = "0.1"
