[package]
name = "lc_api"
version = "0.1.0"
authors = ["Bobby Reynolds <bobby@reynoldsbd.net>"]
edition = "2018"

[dependencies]
diesel = {version = "1.4", features = ["r2d2", "sqlite"] }
serde = { version = "1.0", features = ["derive"] }
