[package]
name = "lc_api"
version = "0.1.0"
authors = ["Bobby Reynolds <bobby@reynoldsbd.net>"]
edition = "2018"

[dependencies]
actix-web = "1.0"
derive_more = "0.15"
diesel = {version = "1.4", features = ["sqlite"] }
serde = { version = "1.0", features = ["derive"] }
